### ISSUE TITLE
Парсинг существительных в любом падеже

### ISSUE THREAD

**Issue by nvchernov** [PavelTorgashov/LingvoNET#2]
Имеется ли возможность парсить получить существительное, например в родительном падеже? Например - хочу получить море в родительном падеже (моря) или винительном (морю) с помощью FindOne

**Comment by PavelTorgashov** [comment]
Если у вас есть исходная форма (единственное число, именительный падеж) - да вы можете получить любой падеж. Эта библиотека для этого и предназначена.
